# Generated by Django 4.1.1 on 2022-09-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_user_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='user_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name="this job's due"),
        ),
    ]
