# Generated by Django 4.1.1 on 2022-09-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_user_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
