# Generated by Django 4.1.2 on 2023-02-18 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobs', models.PositiveIntegerField(verbose_name='your done jobs count goal')),
                ('hours', models.PositiveIntegerField(verbose_name='your spent hours goal')),
                ('measure', models.CharField(choices=[('t', 'Today'), ('w', 'This week'), ('m', 'This month')], max_length=1, verbose_name='the measure of your goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
