# Generated by Django 4.1.2 on 2023-02-26 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
