# Generated by Django 4.1.2 on 2022-11-27 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_lists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='your Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='your Full Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='your Message'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='your Phone Number'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date time created'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='group_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='group_lists.grouplist', verbose_name='group list'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='user_receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='the receiver user'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='user_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='the sender user'),
        ),
    ]
