# Generated by Django 4.1.2 on 2023-03-28 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0005_remove_job_user_time_alter_job_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Habit title')),
                ('description', models.TextField(max_length=300, verbose_name='Habit description')),
                ('repetitiveness', models.CharField(choices=[('e', 'Everyday'), ('w', 'Specific days in week'), ('m', 'Specific days in month')], max_length=1, verbose_name='Habit repetitiveness')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Habit start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Habit end date')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('todo_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.todo', verbose_name='Habit To-do list')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
