# Generated by Django 4.1.2 on 2022-12-17 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='visible',
        ),
    ]
