# Generated by Django 4.1.2 on 2022-12-11 00:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_job_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='user_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 12, 11, 0, 53, 48, 543749, tzinfo=datetime.timezone.utc), null=True, verbose_name='job date'),
        ),
    ]
