# Generated by Django 4.1.2 on 2022-12-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_job_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='duration',
            field=models.TimeField(blank=True, null=True, verbose_name='job duration'),
        ),
    ]
