# Generated by Django 4.1.2 on 2022-10-31 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_job_text_alter_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='text',
            field=models.CharField(max_length=300, verbose_name='your job text'),
        ),
    ]
