# Generated by Django 4.1.2 on 2022-11-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_job_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='user_datetime',
        ),
        migrations.AddField(
            model_name='job',
            name='user_date',
            field=models.DateField(blank=True, null=True, verbose_name='job date'),
        ),
        migrations.AddField(
            model_name='job',
            name='user_time',
            field=models.TimeField(blank=True, null=True, verbose_name='job time'),
        ),
    ]
