# Generated by Django 4.1.2 on 2022-10-26 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_job_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
    ]
