# Generated by Django 4.1.2 on 2022-12-11 00:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_job_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='user_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='job date'),
        ),
    ]
