# Generated by Django 4.1.2 on 2023-01-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_job_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='job notes'),
        ),
    ]
