# Generated by Django 4.1.2 on 2022-11-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_job_user_datetime_job_user_date_job_user_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='datetime_modified',
        ),
        migrations.AddField(
            model_name='job',
            name='user_done_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
