# Generated by Django 4.1.2 on 2023-03-09 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0004_job_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='user_time',
        ),
        migrations.AlterField(
            model_name='job',
            name='text',
            field=models.CharField(max_length=300, verbose_name='your job text'),
        ),
        migrations.AlterField(
            model_name='job',
            name='user_done_date',
            field=models.DateField(blank=True, null=True, verbose_name='done date'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Todo-list name'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL, verbose_name='Todo-list owner'),
        ),
    ]
