# Generated by Django 4.1.2 on 2022-11-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_remove_job_datetime_modified_job_user_done_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='user_done_datetime',
        ),
        migrations.AddField(
            model_name='job',
            name='user_done_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
