# Generated by Django 4.1.2 on 2022-12-11 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_alter_job_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='user_date',
            field=models.DateField(blank=True, null=True, verbose_name='job date'),
        ),
    ]
