# Generated by Django 4.1.2 on 2022-12-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_alter_job_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='text',
            field=models.CharField(error_messages={'required': 'Please enter job text'}, max_length=300, verbose_name='your job text'),
        ),
    ]
