# Generated by Django 4.1.2 on 2023-02-18 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
