# Generated by Django 4.1.1 on 2022-10-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_address_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='task_completed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
