# Generated by Django 4.1.2 on 2023-02-24 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_all_jobs_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='all_jobs_done',
        ),
    ]
