# Generated by Django 4.1.2 on 2022-12-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='all_jobs_done',
            field=models.PositiveIntegerField(default=0, verbose_name='all jobs done'),
        ),
    ]
