# Generated by Django 4.1.1 on 2022-10-01 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_task_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='task_completed',
        ),
    ]
