# Generated by Django 4.1.7 on 2023-03-06 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0005_remove_job_user_time_alter_job_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='Group title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='group description')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='group_pics/', verbose_name='group Picture')),
                ('enable_chat', models.BooleanField(default=True, verbose_name='Group members chat')),
                ('enable_job_divider', models.BooleanField(default=False, verbose_name='Group job divider')),
                ('admins', models.ManyToManyField(blank=True, related_name='group_lists_as_admin', to=settings.AUTH_USER_MODEL, verbose_name='Group admins')),
                ('members', models.ManyToManyField(blank=True, related_name='group_lists_as_member', to=settings.AUTH_USER_MODEL, verbose_name='member users')),
                ('todos', models.ManyToManyField(related_name='group_todos', to='todo.todo')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='date time created')),
                ('group_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='group_lists.grouplist', verbose_name='group list')),
                ('user_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='the receiver user')),
                ('user_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='the sender user')),
            ],
        ),
    ]
