# Generated by Django 4.1.2 on 2023-02-09 04:52

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('todo', '0004_job_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='Group title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='group description')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='group_pics/', verbose_name='group Picture')),
                ('enable_chat', models.BooleanField(default=True, verbose_name='Group members chat')),
                ('enable_job_divider', models.BooleanField(default=False, verbose_name='Group job divider')),
                ('slug', models.SlugField()),
                ('admins', models.ManyToManyField(blank=True, related_name='as_admin', to=settings.AUTH_USER_MODEL, verbose_name='Group admins')),
                ('members', models.ManyToManyField(blank=True, related_name='as_member', to=settings.AUTH_USER_MODEL, verbose_name='member users')),
                ('todo', models.ManyToManyField(related_name='group_todos', to='todo.todo')),
            ],
        ),
    ]
