# Generated by Django 4.1.2 on 2023-03-09 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0005_remove_job_user_time_alter_job_text_and_more'),
        ('group_lists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouplist',
            name='todo',
        ),
        migrations.RemoveField(
            model_name='grouplist',
            name='users',
        ),
        migrations.AddField(
            model_name='grouplist',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='group_lists_as_admin', to=settings.AUTH_USER_MODEL, verbose_name='Group admins'),
        ),
        migrations.AddField(
            model_name='grouplist',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='group description'),
        ),
        migrations.AddField(
            model_name='grouplist',
            name='enable_chat',
            field=models.BooleanField(default=True, verbose_name='Group members chat'),
        ),
        migrations.AddField(
            model_name='grouplist',
            name='enable_job_divider',
            field=models.BooleanField(default=False, verbose_name='Group job divider'),
        ),
        migrations.AddField(
            model_name='grouplist',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='group_lists_as_member', to=settings.AUTH_USER_MODEL, verbose_name='member users'),
        ),
        migrations.AddField(
            model_name='grouplist',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='group_pics/', verbose_name='group Picture'),
        ),
        migrations.AddField(
            model_name='grouplist',
            name='title',
            field=models.CharField(default='group_title', max_length=200, verbose_name='Group title'),
        ),
        migrations.AddField(
            model_name='grouplist',
            name='todos',
            field=models.ManyToManyField(related_name='group_todos', to='todo.todo'),
        ),
        migrations.AddField(
            model_name='grouplist',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='date time created')),
                ('group_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='group_lists.grouplist', verbose_name='group list')),
                ('user_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='the receiver user')),
                ('user_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='the sender user')),
            ],
        ),
    ]
