# Generated by Django 4.1.2 on 2023-02-11 09:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group_lists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouplist',
            name='slug',
        ),
        migrations.AlterField(
            model_name='grouplist',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='group_lists_as_admin', to=settings.AUTH_USER_MODEL, verbose_name='Group admins'),
        ),
        migrations.AlterField(
            model_name='grouplist',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='group_lists_as_member', to=settings.AUTH_USER_MODEL, verbose_name='member users'),
        ),
    ]
