# Generated by Django 4.1.2 on 2023-01-29 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_job_notes'),
        ('group_lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouplist',
            name='title',
            field=models.CharField(default='hello', max_length=200, verbose_name='Group title'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='grouplist',
            name='todo',
        ),
        migrations.AddField(
            model_name='grouplist',
            name='todo',
            field=models.ManyToManyField(related_name='group_todos', to='todo.todo'),
        ),
    ]
