# Generated by Django 4.1.2 on 2023-01-30 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group_lists', '0002_grouplist_title_remove_grouplist_todo_grouplist_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouplist',
            old_name='users',
            new_name='members',
        ),
        migrations.AddField(
            model_name='grouplist',
            name='admins',
            field=models.ManyToManyField(related_name='group_admins', to=settings.AUTH_USER_MODEL, verbose_name='Group admins'),
        ),
        migrations.AddField(
            model_name='grouplist',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='group description'),
        ),
        migrations.AddField(
            model_name='grouplist',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='group_pics/', verbose_name='group Picture'),
        ),
    ]
