# Generated by Django 4.1.2 on 2023-03-09 08:48
import uuid

from django.db import migrations


def get_uuid(app, schema_editor):
    model = app.get_model('group_lists', 'GroupList')
    for row in model.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):
    dependencies = [
        ('group_lists', '0002_remove_grouplist_todo_remove_grouplist_users_and_more'),
    ]

    operations = [
        migrations.RunPython(get_uuid, reverse_code=migrations.RunPython.noop)
    ]
