# Generated by Django 4.1.2 on 2023-03-09 08:48

from django.db import migrations
from django.db import models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('group_lists', '0003_auto_20230309_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouplist',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
