# Generated by Django 4.1.2 on 2023-01-31 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_lists', '0003_rename_users_grouplist_members_grouplist_admins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouplist',
            name='enable_chat',
            field=models.BooleanField(default=True, verbose_name='Group members chat'),
        ),
        migrations.AddField(
            model_name='grouplist',
            name='enable_job_divider',
            field=models.BooleanField(default=False, verbose_name='Group job divider'),
        ),
    ]
