# Generated by Django 4.1.2 on 2023-02-27 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_lists', '0003_invitation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouplist',
            old_name='todo',
            new_name='todos',
        ),
    ]
