# Generated by Django 4.1.2 on 2023-02-04 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group_lists', '0004_grouplist_enable_chat_grouplist_enable_job_divider'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouplist',
            name='slug',
            field=models.SlugField(default='hello-world'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grouplist',
            name='admins',
            field=models.ManyToManyField(related_name='as_admin', to=settings.AUTH_USER_MODEL, verbose_name='Group admins'),
        ),
        migrations.AlterField(
            model_name='grouplist',
            name='members',
            field=models.ManyToManyField(related_name='as_member', to=settings.AUTH_USER_MODEL, verbose_name='member users'),
        ),
    ]
