# Generated by Django 4.1.2 on 2023-03-18 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_lists', '0004_auto_20230309_1218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
