# Generated by Django 4.1.2 on 2023-02-11 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_lists', '0002_remove_grouplist_slug_alter_grouplist_admins_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_lists.grouplist', verbose_name='Message group'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Message sender'),
        ),
        migrations.AlterField(
            model_name='onlineusers',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_users', to='group_lists.grouplist', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='onlineusers',
            name='online_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Group online users'),
        ),
    ]
