# Generated by Django 4.1.2 on 2023-02-27 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_lists', '0004_rename_todo_grouplist_todos'),
        ('chats', '0003_alter_message_group_alter_message_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='group_lists.grouplist', verbose_name='Message group'),
        ),
    ]
